### ISSUE TITLE
Can I add my esolang?

### ISSUE THREAD

**Issue by TurnipGuy30** [iolivia/fizzbuzz#19]
Hi @iolivia,
I'm currently making an esolang called [Prado](https://github.com/TurnipGuy30/Prado) that directly translates to BF. Can I please make a PR with a Prado copy of the `.bf` file? As of right now, I'm still making the BF->Prado translator, so it would be a manual task, which is why I'm asking first. But if you don't respond, I'll probably do it anyway!
Thanks!

**Comment by iolivia** [comment]
Yeah, why not? Looking forward to seeing it! 🚀

**Comment by TurnipGuy30** [comment]
OK thanks! It'll be done soon, look out for the PR!
